#!/bin/sh

set -e

if dpkg-maintscript-helper supports mv_conffile; then
  dpkg-maintscript-helper mv_conffile \
    /etc/lightdm/lightdm-gtk-greeter-ubuntu.conf \
    /etc/lightdm/lightdm-gtk-greeter.conf.d/01_ubuntu.conf \
    2.0.1-1ubuntu1 -- "$@"
fi

if [ "$1" = "configure" ]; then
  update-alternatives --install /usr/share/xgreeters/lightdm-greeter.desktop \
  lightdm-greeter /usr/share/xgreeters/lightdm-gtk-greeter.desktop 60
fi

#DEBHELPER#

exit 0
