/* automatically generated from lightdm-gtk-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.4\"/><requires lib=\"greeter_menu_bar\" version=\"1.0\""
  "/><object class=\"GtkAccelGroup\" id=\"a11y_accelgroup\"/><object class"
  "=\"GtkAccelGroup\" id=\"power_accelgroup\"/><object class=\"GtkEventBox"
  "\" id=\"panel_window\"><property name=\"name\">panel_window</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"valign\">start</property><child><object"
  " class=\"GreeterMenuBar\" id=\"menubar\"><property name=\"name\">menuba"
  "r</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"pack_direction\">rtl</prop"
  "erty><signal name=\"key-press-event\" handler=\"menubar_key_press_cb\" "
  "swapped=\"no\"/><child><object class=\"GtkMenuItem\" id=\"power_menuite"
  "m\"><property name=\"name\">power_menuitem</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><c"
  "hild type=\"submenu\"><object class=\"GtkMenu\" id=\"power_menu\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"accel_group\">power_accelgroup</property><c"
  "hild><object class=\"GtkMenuItem\" id=\"suspend_menuitem\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">Suspend</property><si"
  "gnal name=\"activate\" handler=\"suspend_cb\" swapped=\"no\"/></object>"
  "</child><child><object class=\"GtkMenuItem\" id=\"hibernate_menuitem\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">Hibernate"
  "</property><signal name=\"activate\" handler=\"hibernate_cb\" swapped=\""
  "no\"/></object></child><child><object class=\"GtkMenuItem\" id=\"restar"
  "t_menuitem\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Restart...</property><signal name=\"activate\" handler=\"restart_cb\""
  " swapped=\"no\"/></object></child><child><object class=\"GtkMenuItem\" "
  "id=\"shutdown_menuitem\"><property name=\"use_action_appearance\">False"
  "</property><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"accel_path\">&lt;Login&gt;/"
  "power/shutdown</property><property name=\"label\" translatable=\"yes\">"
  "Shut Down...</property><signal name=\"activate\" handler=\"shutdown_cb\""
  " swapped=\"no\"/></object></child></object></child></object></child><ch"
  "ild><object class=\"GtkMenuItem\" id=\"a11y_menuitem\"><property name=\""
  "name\">a11y_menuitem</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><child type=\"submenu\">"
  "<object class=\"GtkMenu\" id=\"a11y_menu\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"accel_group\">a11y_accelgroup</property><child><object class=\"Gtk"
  "CheckMenuItem\" id=\"large_font_menuitem\"><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"accel_pat"
  "h\">&lt;Login&gt;/a11y/font</property><property name=\"label\" translat"
  "able=\"yes\">Large Font</property><signal name=\"toggled\" handler=\"a1"
  "1y_font_cb\" swapped=\"no\"/></object></child><child><object class=\"Gt"
  "kCheckMenuItem\" id=\"high_contrast_menuitem\"><property name=\"use_act"
  "ion_appearance\">False</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"accel"
  "_path\">&lt;Login&gt;/a11y/contrast</property><property name=\"label\" "
  "translatable=\"yes\">High Contrast</property><signal name=\"toggled\" h"
  "andler=\"a11y_contrast_cb\" swapped=\"no\"/></object></child><child><ob"
  "ject class=\"GtkCheckMenuItem\" id=\"keyboard_menuitem\"><property name"
  "=\"use_action_appearance\">False</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"accel_path\">&lt;Login&gt;/a11y/keyboard</property><property name="
  "\"label\" translatable=\"yes\">On Screen Keyboard</property><property n"
  "ame=\"use_underline\">True</property><signal name=\"toggled\" handler=\""
  "a11y_keyboard_cb\" swapped=\"no\"/></object></child><child><object clas"
  "s=\"GtkCheckMenuItem\" id=\"reader_menuitem\"><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"accel_"
  "path\">&lt;Login&gt;/a11y/reader</property><property name=\"label\" tra"
  "nslatable=\"yes\">Screen Reader</property><property name=\"use_underlin"
  "e\">True</property><signal name=\"toggled\" handler=\"a11y_reader_cb\" "
  "swapped=\"no\"/></object></child></object></child></object></child><chi"
  "ld><object class=\"GtkMenuItem\" id=\"language_menuitem\"><property nam"
  "e=\"name\">language_menuitem</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\">[language_code]</property><child type=\"submenu\"><object class"
  "=\"GtkMenu\" id=\"language_menu\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property></object></child></ob"
  "ject></child><child><object class=\"GtkMenuItem\" id=\"session_menuitem"
  "\"><property name=\"name\">session_menuitem</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "child type=\"submenu\"><object class=\"GtkMenu\" id=\"session_menu\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property></object></child></object></child><child><object class=\""
  "GtkMenuItem\" id=\"layout_menuitem\"><property name=\"name\">layout_men"
  "uitem</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\">[layout]</prop"
  "erty><child type=\"submenu\"><object class=\"GtkMenu\" id=\"layout_menu"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property></object></child></object></child><child><object cla"
  "ss=\"GtkSeparatorMenuItem\" id=\"clock_menuitem\"><property name=\"name"
  "\">clock_menuitem</property><property name=\"can_focus\">False</propert"
  "y></object></child><child><object class=\"GtkSeparatorMenuItem\" id=\"h"
  "ost_menuitem\"><property name=\"name\">host_menuitem</property><propert"
  "y name=\"can_focus\">False</property></object></child></object></child>"
  "<style><class name=\"background\"/></style></object><object class=\"Gtk"
  "EventBox\" id=\"power_window\"><property name=\"name\">power_window</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ha"
  "lign\">center</property><property name=\"valign\">center</property><sig"
  "nal name=\"key-press-event\" handler=\"power_window_key_press_event_cb\""
  " swapped=\"no\"/><child><object class=\"GtkBox\" id=\"box3\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"orientation\">vertical</property><child><object "
  "class=\"GtkEventBox\" id=\"power_content_frame\"><property name=\"name\""
  ">content_frame</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><child><object class=\"GtkGrid"
  "\" id=\"grid2\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"margin_left\">24</prop"
  "erty><property name=\"margin_right\">24</property><property name=\"marg"
  "in_top\">24</property><property name=\"margin_bottom\">24</property><pr"
  "operty name=\"row_spacing\">6</property><property name=\"column_spacing"
  "\">6</property><child><object class=\"GtkImage\" id=\"power_icon\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"margin_left\">6</property><property name=\""
  "margin_right\">12</property><property name=\"margin_top\">6</property><"
  "property name=\"margin_bottom\">6</property><property name=\"stock\">gt"
  "k-missing-image</property></object><packing><property name=\"left_attac"
  "h\">0</property><property name=\"top_attach\">0</property><property nam"
  "e=\"height\">2</property></packing></child><child><object class=\"GtkLa"
  "bel\" id=\"power_title\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"halign\">star"
  "t</property><property name=\"margin_bottom\">6</property><property name"
  "=\"hexpand\">True</property><property name=\"label\">[title]</property>"
  "<attributes><attribute name=\"weight\" value=\"semibold\"/></attributes"
  "></object><packing><property name=\"left_attach\">1</property><property"
  " name=\"top_attach\">0</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"power_text\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"halign"
  "\">start</property><property name=\"hexpand\">True</property><property "
  "name=\"label\">[text]</property></object><packing><property name=\"left"
  "_attach\">1</property><property name=\"top_attach\">1</property></packi"
  "ng></child></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkEv"
  "entBox\" id=\"power_buttonbox_frame\"><property name=\"name\">buttonbox"
  "_frame</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><child><object class=\"GtkButtonBox\" "
  "id=\"buttonbox1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"margin_left\">24</pr"
  "operty><property name=\"margin_right\">24</property><property name=\"ma"
  "rgin_top\">24</property><property name=\"margin_bottom\">24</property><"
  "property name=\"spacing\">6</property><property name=\"layout_style\">e"
  "nd</property><child><object class=\"GtkButton\" id=\"power_cancel_butto"
  "n\"><property name=\"label\" translatable=\"yes\">Cancel</property><pro"
  "perty name=\"name\">cancel_button</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><signal name=\"clicked\" handle"
  "r=\"power_button_clicked_cb\" swapped=\"no\"/></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkButton\" id=\"power_ok_button\"><property name=\"label\""
  " translatable=\"yes\">OK</property><property name=\"name\">power_ok_but"
  "ton</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><signal name=\"clicked\" handler=\"power_button_clicked_cb\" "
  "swapped=\"no\"/></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "></child><style><class name=\"background\"/></style></object><object cl"
  "ass=\"GtkOverlay\" id=\"screen_overlay\"><property name=\"name\">screen"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"hexpand\">True</property><property name=\"vexpand\">True</property><s"
  "ignal name=\"get-child-position\" handler=\"screen_overlay_get_child_po"
  "sition_cb\" swapped=\"no\"/><child><object class=\"GtkEventBox\" id=\"s"
  "creen_overlay_child\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><child><placeholder/></child></ob"
  "ject></child><style><class name=\"lightdm-gtk-greeter\"/></style></obje"
  "ct><object class=\"GtkListStore\" id=\"user_liststore\"><columns><colum"
  "n type=\"gchararray\"/><column type=\"gchararray\"/><column type=\"gint"
  "\"/></columns></object><object class=\"GtkEventBox\" id=\"login_window\""
  "><property name=\"name\">login_window</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"halign\">start</property><property name=\"valign\">start</pro"
  "perty><child><object class=\"GtkBox\" id=\"login_box\"><property name=\""
  "name\">login_box</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"orientation"
  "\">vertical</property><child><object class=\"GtkFrame\" id=\"content_fr"
  "ame\"><property name=\"name\">content_frame</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkGrid\" id=\"grid1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"margin_left\">24</property><property name=\"m"
  "argin_right\">24</property><property name=\"margin_top\">24</property><"
  "property name=\"row_spacing\">6</property><property name=\"column_spaci"
  "ng\">18</property><child><object class=\"GtkFrame\" id=\"user_image_bor"
  "der\"><property name=\"name\">user_image_border</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"halign\">center</property><property name=\"valign\""
  ">center</property><property name=\"label_xalign\">0</property><property"
  " name=\"shadow_type\">none</property><child><object class=\"GtkImage\" "
  "id=\"user_image\"><property name=\"name\">user_image</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"pixel_size\">80</property><property name=\"ico"
  "n_name\">avatar-default</property></object></child></object><packing><p"
  "roperty name=\"left_attach\">0</property><property name=\"top_attach\">"
  "0</property><property name=\"height\">3</property></packing></child><ch"
  "ild><object class=\"GtkComboBox\" id=\"user_combobox\"><property name=\""
  "name\">user_combobox</property><property name=\"width_request\">200</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"va"
  "lign\">center</property><property name=\"margin_top\">12</property><pro"
  "perty name=\"hexpand\">True</property><property name=\"model\">user_lis"
  "tstore</property><signal name=\"changed\" handler=\"user_combobox_activ"
  "e_changed_cb\" swapped=\"no\"/><signal name=\"key-press-event\" handler"
  "=\"user_combo_key_press_cb\" swapped=\"no\"/><child><object class=\"Gtk"
  "CellRendererText\" id=\"cellrenderertext1\"/><attributes><attribute nam"
  "e=\"text\">1</attribute><attribute name=\"weight\">2</attribute></attri"
  "butes></child></object><packing><property name=\"left_attach\">1</prope"
  "rty><property name=\"top_attach\">0</property></packing></child><child>"
  "<object class=\"GtkEntry\" id=\"username_entry\"><property name=\"name\""
  ">prompt_entry</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"hexpand\">True</property><property name=\"invisible_char\""
  ">\342\200\242</property><property name=\"placeholder_text\" translatabl"
  "e=\"yes\">Enter your username</property><signal name=\"focus-out-event\""
  " handler=\"username_focus_out_cb\" swapped=\"no\"/><signal name=\"key-p"
  "ress-event\" handler=\"username_key_press_cb\" swapped=\"no\"/></object"
  "><packing><property name=\"left_attach\">1</property><property name=\"t"
  "op_attach\">1</property></packing></child><child><object class=\"GtkEnt"
  "ry\" id=\"password_entry\"><property name=\"name\">prompt_entry</proper"
  "ty><property name=\"width_request\">200</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"margin_bottom\">12</property><property name=\"hexpand\">True"
  "</property><property name=\"visibility\">False</property><property name"
  "=\"invisible_char\">\342\200\242</property><property name=\"primary_ico"
  "n_activatable\">False</property><property name=\"secondary_icon_activat"
  "able\">False</property><property name=\"placeholder_text\" translatable"
  "=\"yes\">Enter your password</property><signal name=\"activate\" handle"
  "r=\"login_cb\" swapped=\"no\"/><signal name=\"key-press-event\" handler"
  "=\"password_key_press_cb\" swapped=\"no\"/></object><packing><property "
  "name=\"left_attach\">1</property><property name=\"top_attach\">2</prope"
  "rty></packing></child></object></child><child type=\"label_item\"><plac"
  "eholder/></child></object><packing><property name=\"expand\">True</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkInfoBar\" id=\""
  "greeter_infobar\"><property name=\"name\">greeter_infobar</property><pr"
  "operty name=\"can_focus\">False</property><child internal-child=\"actio"
  "n_area\"><object class=\"GtkButtonBox\" id=\"infobar-action_area\"><pro"
  "perty name=\"can_focus\">False</property><property name=\"layout_style\""
  ">end</property><child><placeholder/></child></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">-1</property></packing></child><child int"
  "ernal-child=\"content_area\"><object class=\"GtkBox\" id=\"infobar-cont"
  "ent_area\"><property name=\"can_focus\">False</property><child><object "
  "class=\"GtkLabel\" id=\"message_label\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" comments=\"This is a placeholder string and will be replaced "
  "with a message from PAM\">[message]</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">0</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">-1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkFrame\" id=\"buttonbox_fra"
  "me\"><property name=\"name\">buttonbox_frame</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkBox\" id=\"box2\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"margin_left\">24</property><property name=\"mar"
  "gin_right\">24</property><property name=\"margin_bottom\">24</property>"
  "<child><object class=\"GtkButton\" id=\"cancel_button\"><property name="
  "\"label\" translatable=\"yes\">Cancel</property><property name=\"name\""
  ">cancel_button</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">False</property><signal name=\"clicked\" handler=\"cancel_cb\" swa"
  "pped=\"no\"/></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkButton\" id=\"log"
  "in_button\"><property name=\"label\" translatable=\"yes\">Log In</prope"
  "rty><property name=\"name\">login_button</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"receives_default\">False</property><signal name=\"clicked\""
  " handler=\"login_cb\" swapped=\"no\"/></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"pack_type\">end</property><property name=\"position\">1</pr"
  "operty></packing></child></object></child><child type=\"label_item\"><p"
  "laceholder/></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">2</property></packing></child></object></child><style><class name="
  "\"background\"/></style></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 18801u;

